env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 888
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
girl:
  name: lili
  age: 19
